name: ci

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CMAKE_GENERATOR: Unix Makefiles

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: cmake -Bbuild -DPICO_BUILD=OFF

    - name: build
      run: cmake --build build

    - name: test
      run: ctest --test-dir build -V
